<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use App\Currencies;

class CurrenciesTablesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	Currencies::create(['value' => 'AFN', 'name' => 'Afgaanse afgani']);
    	Currencies::create(['value' => 'AFA', 'name' => 'Afghan Afghani (1927–2002)']);
    	Currencies::create(['value' => 'ALL', 'name' => 'Albanese lek']);
    	Currencies::create(['value' => 'ALK', 'name' => 'Albanian Lek (1946–1965)']);
    	Currencies::create(['value' => 'DZD', 'name' => 'Algeriese dinar']);
    	Currencies::create(['value' => 'USD', 'name' => 'Amerikaanse dollar']);
    	Currencies::create(['value' => 'ADP', 'name' => 'Andorran Peseta']);
    	Currencies::create(['value' => 'AOK', 'name' => 'Angolan Kwanza (1977–1991)']);
    	Currencies::create(['value' => 'AON', 'name' => 'Angolan New Kwanza (1990–2000)']);
    	Currencies::create(['value' => 'AOR', 'name' => 'Angolan Readjusted Kwanza (1995–1999)']);
    	Currencies::create(['value' => 'AOA', 'name' => 'Angolese kwanza']);
    	Currencies::create(['value' => 'ARA', 'name' => 'Argentine Austral']);
    	Currencies::create(['value' => 'ARM', 'name' => 'Argentine Peso (1881–1970)']);
    	Currencies::create(['value' => 'ARP', 'name' => 'Argentine Peso (1983–1985)']);
    	Currencies::create(['value' => 'ARL', 'name' => 'Argentine Peso Ley (1970–1983)']);
    	Currencies::create(['value' => 'ARS', 'name' => 'Argentynse peso']);
    	Currencies::create(['value' => 'AMD', 'name' => 'Armeense dram']);
    	Currencies::create(['value' => 'AWG', 'name' => 'Arubaanse floryn']);
    	Currencies::create(['value' => 'AUD', 'name' => 'Australiese dollar']);
    	Currencies::create(['value' => 'ATS', 'name' => 'Austrian Schilling']);
    	Currencies::create(['value' => 'AZM', 'name' => 'Azerbaijani Manat (1993–2006)']);
    	Currencies::create(['value' => 'AZN', 'name' => 'Azerbeidjaanse manat']);
    	Currencies::create(['value' => 'BSD', 'name' => 'Bahamiaanse dollar']);
    	Currencies::create(['value' => 'BHD', 'name' => 'Bahreinse dinar']);
    	Currencies::create(['value' => 'BDT', 'name' => 'Bangladesjiese taka']);
    	Currencies::create(['value' => 'BBD', 'name' => 'Barbados-dollar']);
    	Currencies::create(['value' => 'BYB', 'name' => 'Belarusian Ruble (1994–1999)']);
    	Currencies::create(['value' => 'BEF', 'name' => 'Belgian Franc']);
    	Currencies::create(['value' => 'BEC', 'name' => 'Belgian Franc (convertible)']);
    	Currencies::create(['value' => 'BEL', 'name' => 'Belgian Franc (financial)']);
    	Currencies::create(['value' => 'BZD', 'name' => 'Beliziese dollar']);
    	Currencies::create(['value' => 'BYN', 'name' => 'Belo-Russiese roebel']);
    	Currencies::create(['value' => 'BYR', 'name' => 'Belo-Russiese roebel (2000–2016)']);
    	Currencies::create(['value' => 'BMD', 'name' => 'Bermuda-dollar']);
    	Currencies::create(['value' => 'BTN', 'name' => 'Bhoetanese ngoeltroem']);
    	Currencies::create(['value' => 'BOB', 'name' => 'Boliviaanse boliviano']);
    	Currencies::create(['value' => 'BOL', 'name' => 'Bolivian Boliviano (1863–1963)']);
    	Currencies::create(['value' => 'BOV', 'name' => 'Bolivian Mvdol']);
    	Currencies::create(['value' => 'BOP', 'name' => 'Bolivian Peso']);
    	Currencies::create(['value' => 'BAD', 'name' => 'Bosnia-Herzegovina Dinar (1992–1994)']);
    	Currencies::create(['value' => 'BAN', 'name' => 'Bosnia-Herzegovina New Dinar (1994–1997)']);
    	Currencies::create(['value' => 'BAM', 'name' => 'Bosnies-Herzegowiniese omskakelbare marka']);
    	Currencies::create(['value' => 'BWP', 'name' => 'Botswana pula']);
    	Currencies::create(['value' => 'BRL', 'name' => 'Brasilliaanse reaal']);
    	Currencies::create(['value' => 'BRC', 'name' => 'Brazilian Cruzado (1986–1989)']);
    	Currencies::create(['value' => 'BRZ', 'name' => 'Brazilian Cruzeiro (1942–1967)']);
    	Currencies::create(['value' => 'BRE', 'name' => 'Brazilian Cruzeiro (1990–1993)']);
    	Currencies::create(['value' => 'BRR', 'name' => 'Brazilian Cruzeiro (1993–1994)']);
    	Currencies::create(['value' => 'BRN', 'name' => 'Brazilian New Cruzado (1989–1990)']);
    	Currencies::create(['value' => 'BRB', 'name' => 'Brazilian New Cruzeiro (1967–1986)']);
    	Currencies::create(['value' => 'GBP', 'name' => 'Britse pond']);
    	Currencies::create(['value' => 'BND', 'name' => 'Broeneise dollar']);
    	Currencies::create(['value' => 'BGN', 'name' => 'Bulgaarse lev']);
    	Currencies::create(['value' => 'BGL', 'name' => 'Bulgarian Hard Lev']);
    	Currencies::create(['value' => 'BGO', 'name' => 'Bulgarian Lev (1879–1952)']);
    	Currencies::create(['value' => 'BGM', 'name' => 'Bulgarian Socialist Lev']);
    	Currencies::create(['value' => 'BUK', 'name' => 'Burmese Kyat']);
    	Currencies::create(['value' => 'BIF', 'name' => 'Burundiese frank']);
    	Currencies::create(['value' => 'XOF', 'name' => 'CFA frank BCEAO']);
    	Currencies::create(['value' => 'XAF', 'name' => 'CFA frank BEAC']);
    	Currencies::create(['value' => 'XPF', 'name' => 'CFP-frank']);
    	Currencies::create(['value' => 'KYD', 'name' => 'Cayman-eilande dollar']);
    	Currencies::create(['value' => 'CLE', 'name' => 'Chilean Escudo']);
    	Currencies::create(['value' => 'CLF', 'name' => 'Chilean Unit of Account (UF)']);
    	Currencies::create(['value' => 'CLP', 'name' => 'Chileense peso']);
    	Currencies::create(['value' => 'CNX', 'name' => 'Chinese People’s Bank Dollar']);
    	Currencies::create(['value' => 'COP', 'name' => 'Colombiaanse peso']);
    	Currencies::create(['value' => 'COU', 'name' => 'Colombian Real Value Unit']);
    	Currencies::create(['value' => 'KMF', 'name' => 'Comoraanse frank']);
    	Currencies::create(['value' => 'CRC', 'name' => 'Costa Ricaanse colón']);
    	Currencies::create(['value' => 'HRD', 'name' => 'Croatian Dinar']);
    	Currencies::create(['value' => 'CYP', 'name' => 'Cypriot Pound']);
    	Currencies::create(['value' => 'CSK', 'name' => 'Czechoslovak Hard Koruna']);
    	Currencies::create(['value' => 'DKK', 'name' => 'Deense kroon']);
    	Currencies::create(['value' => 'DJF', 'name' => 'Djiboeti frank']);
    	Currencies::create(['value' => 'DOP', 'name' => 'Dominikaanse peso']);
    	Currencies::create(['value' => 'NLG', 'name' => 'Dutch Guilder']);
    	Currencies::create(['value' => 'DDM', 'name' => 'East German Mark']);
    	Currencies::create(['value' => 'ECS', 'name' => 'Ecuadorian Sucre']);
    	Currencies::create(['value' => 'ECV', 'name' => 'Ecuadorian Unit of Constant Value']);
    	Currencies::create(['value' => 'EGP', 'name' => 'Egiptiese pond']);
    	Currencies::create(['value' => 'GQE', 'name' => 'Equatorial Guinean Ekwele']);
    	Currencies::create(['value' => 'ERN', 'name' => 'Eritrese nakfa']);
    	Currencies::create(['value' => 'EEK', 'name' => 'Estonian Kroon']);
    	Currencies::create(['value' => 'ETB', 'name' => 'Etiopiese birr']);
    	Currencies::create(['value' => 'EUR', 'name' => 'Euro']);
    	Currencies::create(['value' => 'XEU', 'name' => 'European Currency Unit']);
    	Currencies::create(['value' => 'FKP', 'name' => 'Falkland-eilande pond']);
    	Currencies::create(['value' => 'FJD', 'name' => 'Fidjiaanse dollar']);
    	Currencies::create(['value' => 'PHP', 'name' => 'Filippynse peso']);
    	Currencies::create(['value' => 'FIM', 'name' => 'Finnish Markka']);
    	Currencies::create(['value' => 'FRF', 'name' => 'French Franc']);
    	Currencies::create(['value' => 'XFO', 'name' => 'French Gold Franc']);
    	Currencies::create(['value' => 'XFU', 'name' => 'French UIC-Franc']);
    	Currencies::create(['value' => 'GMD', 'name' => 'Gambiese dalasi']);
    	Currencies::create(['value' => 'GEK', 'name' => 'Georgian Kupon Larit']);
    	Currencies::create(['value' => 'GEL', 'name' => 'Georgiese lari']);
    	Currencies::create(['value' => 'DEM', 'name' => 'German Mark']);
    	Currencies::create(['value' => 'GHS', 'name' => 'Ghanese cedi']);
    	Currencies::create(['value' => 'GHC', 'name' => 'Ghanese cedi (1979–2007)']);
    	Currencies::create(['value' => 'GIP', 'name' => 'Gibraltarese pond']);
    	Currencies::create(['value' => 'GRD', 'name' => 'Greek Drachma']);
    	Currencies::create(['value' => 'GTQ', 'name' => 'Guatemalaanse quetzal']);
    	Currencies::create(['value' => 'GWP', 'name' => 'Guinea-Bissau Peso']);
    	Currencies::create(['value' => 'GNF', 'name' => 'Guinese frank']);
    	Currencies::create(['value' => 'GNS', 'name' => 'Guinese syli']);
    	Currencies::create(['value' => 'GYD', 'name' => 'Guyanese dollar']);
    	Currencies::create(['value' => 'HTG', 'name' => 'Haïtiaanse gourde']);
    	Currencies::create(['value' => 'HNL', 'name' => 'Hondurese lempira']);
    	Currencies::create(['value' => 'HKD', 'name' => 'Hong Kong dollar']);
    	Currencies::create(['value' => 'HUF', 'name' => 'Hongaarse florint']);
    	Currencies::create(['value' => 'ISJ', 'name' => 'Icelandic Króna (1918–1981)']);
    	Currencies::create(['value' => 'INR', 'name' => 'Indiese roepee']);
    	Currencies::create(['value' => 'IDR', 'name' => 'Indonesiese roepia']);
    	Currencies::create(['value' => 'IQD', 'name' => 'Irakse dinar']);
    	Currencies::create(['value' => 'IRR', 'name' => 'Iranse rial']);
    	Currencies::create(['value' => 'IEP', 'name' => 'Irish Pound']);
    	Currencies::create(['value' => 'ILP', 'name' => 'Israeli Pound']);
    	Currencies::create(['value' => 'ILR', 'name' => 'Israeli Shekel (1980–1985)']);
    	Currencies::create(['value' => 'ILS', 'name' => 'Israeliese nuwe sikkel']);
    	Currencies::create(['value' => 'ITL', 'name' => 'Italiaanse lier']);
    	Currencies::create(['value' => 'JMD', 'name' => 'Jamaikaanse dollar']);
    	Currencies::create(['value' => 'JPY', 'name' => 'Japannese jen']);
    	Currencies::create(['value' => 'YER', 'name' => 'Jemenitiese rial']);
    	Currencies::create(['value' => 'JOD', 'name' => 'Jordaniese dinar']);
    	Currencies::create(['value' => 'CVE', 'name' => 'Kaap Verdiese escudo']);
    	Currencies::create(['value' => 'KHR', 'name' => 'Kambodjaanse riel']);
    	Currencies::create(['value' => 'CAD', 'name' => 'Kanadese dollar']);
    	Currencies::create(['value' => 'QAR', 'name' => 'Katarrese rial']);
    	Currencies::create(['value' => 'KZT', 'name' => 'Kazakse tenge']);
    	Currencies::create(['value' => 'KES', 'name' => 'Keniaanse sjieling']);
    	Currencies::create(['value' => 'KGS', 'name' => 'Kirgisiese som']);
    	Currencies::create(['value' => 'KWD', 'name' => 'Koeweitse dinar']);
    	Currencies::create(['value' => 'CDF', 'name' => 'Kongolese frank']);
    	Currencies::create(['value' => 'HRK', 'name' => 'Kroatiese kuna']);
    	Currencies::create(['value' => 'CUC', 'name' => 'Kubaanse omskakelbare peso']);
    	Currencies::create(['value' => 'CUP', 'name' => 'Kubaanse peso']);
    	Currencies::create(['value' => 'LAK', 'name' => 'Laosiaanse kip']);
    	Currencies::create(['value' => 'LVR', 'name' => 'Latvian Ruble']);
    	Currencies::create(['value' => 'LBP', 'name' => 'Lebanese pond']);
    	Currencies::create(['value' => 'LSL', 'name' => 'Lesotho loti']);
    	Currencies::create(['value' => 'LVL', 'name' => 'Lettiese lats']);
    	Currencies::create(['value' => 'LRD', 'name' => 'Liberiese dollar']);
    	Currencies::create(['value' => 'LYD', 'name' => 'Libiese dinar']);
    	Currencies::create(['value' => 'LTL', 'name' => 'Litause litas']);
    	Currencies::create(['value' => 'LTT', 'name' => 'Lithuanian Talonas']);
    	Currencies::create(['value' => 'LUL', 'name' => 'Luxembourg Financial Franc']);
    	Currencies::create(['value' => 'LUC', 'name' => 'Luxembourgian Convertible Franc']);
    	Currencies::create(['value' => 'LUF', 'name' => 'Luxembourgian Franc']);
    	Currencies::create(['value' => 'MOP', 'name' => 'Macaose pataca']);
    	Currencies::create(['value' => 'MKN', 'name' => 'Macedonian Denar (1992–1993)']);
    	Currencies::create(['value' => 'MKD', 'name' => 'Macedoniese denar']);
    	Currencies::create(['value' => 'MGF', 'name' => 'Malagasy Franc']);
    	Currencies::create(['value' => 'MWK', 'name' => 'Malawiese kwacha']);
    	Currencies::create(['value' => 'MVP', 'name' => 'Maldivian Rupee (1947–1981)']);
    	Currencies::create(['value' => 'MVR', 'name' => 'Malediviese rufia']);
    	Currencies::create(['value' => 'MYR', 'name' => 'Maleisiese ringgit']);
    	Currencies::create(['value' => 'MGA', 'name' => 'Malgassiese ariary']);
    	Currencies::create(['value' => 'MLF', 'name' => 'Malian Franc']);
    	Currencies::create(['value' => 'MTL', 'name' => 'Maltese Lira']);
    	Currencies::create(['value' => 'MTP', 'name' => 'Maltese Pound']);
    	Currencies::create(['value' => 'MAD', 'name' => 'Marokkaanse dirham']);
    	Currencies::create(['value' => 'MRO', 'name' => 'Mauritaniese ouguiya']);
    	Currencies::create(['value' => 'MUR', 'name' => 'Mauritiaanse rupee']);
    	Currencies::create(['value' => 'MXN', 'name' => 'Meksikaanse peso']);
    	Currencies::create(['value' => 'MXV', 'name' => 'Mexican Investment Unit']);
    	Currencies::create(['value' => 'MXP', 'name' => 'Mexican Silver Peso (1861–1992)']);
    	Currencies::create(['value' => 'MMK', 'name' => 'Mianmese kyat']);
    	Currencies::create(['value' => 'MDC', 'name' => 'Moldovan Cupon']);
    	Currencies::create(['value' => 'MDL', 'name' => 'Moldowiese leu']);
    	Currencies::create(['value' => 'MCF', 'name' => 'Monegasque Franc']);
    	Currencies::create(['value' => 'MNT', 'name' => 'Mongoolse toegrik']);
    	Currencies::create(['value' => 'MAF', 'name' => 'Moroccan Franc']);
    	Currencies::create(['value' => 'MZN', 'name' => 'Mosambiekse metical']);
    	Currencies::create(['value' => 'MZM', 'name' => 'Mosambiekse metical (1980–2006)']);
    	Currencies::create(['value' => 'MZE', 'name' => 'Mozambican Escudo']);
    	Currencies::create(['value' => 'NAD', 'name' => 'Namibiese dollar']);
    	Currencies::create(['value' => 'ANG', 'name' => 'Nederlands-Antilliaanse gulde']);
    	Currencies::create(['value' => 'NPR', 'name' => 'Nepalese roepee']);
    	Currencies::create(['value' => 'NIO', 'name' => 'Nicaraguaanse córdoba']);
    	Currencies::create(['value' => 'NIC', 'name' => 'Nicaraguan Córdoba (1988–1991)']);
    	Currencies::create(['value' => 'NZD', 'name' => 'Nieu-Seeland dollar']);
    	Currencies::create(['value' => 'NGN', 'name' => 'Nigeriese naira']);
    	Currencies::create(['value' => 'KPW', 'name' => 'Noord-Koreaanse won']);
    	Currencies::create(['value' => 'NOK', 'name' => 'Noorse kroon']);
    	Currencies::create(['value' => 'TWD', 'name' => 'Nuwe Taiwanese dollar']);
    	Currencies::create(['value' => 'UAH', 'name' => 'Oekraïnse hriwna']);
    	Currencies::create(['value' => 'UZS', 'name' => 'Oezbekiese som']);
    	Currencies::create(['value' => 'OMR', 'name' => 'Omaanse rial']);
    	Currencies::create(['value' => 'XCD', 'name' => 'Oos-Karibbiese dollar']);
    	Currencies::create(['value' => 'PKR', 'name' => 'Pakistanse roepee']);
    	Currencies::create(['value' => 'PAB', 'name' => 'Panamese balboa']);
    	Currencies::create(['value' => 'PGK', 'name' => 'Papoea-Nieu-Guinese kina']);
    	Currencies::create(['value' => 'PYG', 'name' => 'Paraguaanse guarani']);
    	Currencies::create(['value' => 'PEN', 'name' => 'Peruaanse sol']);
    	Currencies::create(['value' => 'PEI', 'name' => 'Peruvian Inti']);
    	Currencies::create(['value' => 'PES', 'name' => 'Peruvian Sol (1863–1965)']);
    	Currencies::create(['value' => 'PLZ', 'name' => 'Polish Zloty (1950–1995)']);
    	Currencies::create(['value' => 'PLN', 'name' => 'Poolse zloty']);
    	Currencies::create(['value' => 'PTE', 'name' => 'Portuguese Escudo']);
    	Currencies::create(['value' => 'GWE', 'name' => 'Portuguese Guinea Escudo']);
    	Currencies::create(['value' => 'XRE', 'name' => 'RINET Funds']);
    	Currencies::create(['value' => 'RHD', 'name' => 'Rhodesian Dollar']);
    	Currencies::create(['value' => 'RON', 'name' => 'Roemeense leu']);
    	Currencies::create(['value' => 'ROL', 'name' => 'Romanian Leu (1952–2006)']);
    	Currencies::create(['value' => 'RUR', 'name' => 'Russian Ruble (1991–1998)']);
    	Currencies::create(['value' => 'RUB', 'name' => 'Russiese roebel']);
    	Currencies::create(['value' => 'RWF', 'name' => 'Rwandiese frank']);
    	Currencies::create(['value' => 'SBD', 'name' => 'Salomonseilande dollar']);
    	Currencies::create(['value' => 'SVC', 'name' => 'Salvadoran Colón']);
    	Currencies::create(['value' => 'WST', 'name' => 'Samoaanse tala']);
    	Currencies::create(['value' => 'SAR', 'name' => 'Saoedi-Arabiese riyal']);
    	Currencies::create(['value' => 'CSD', 'name' => 'Serbian Dinar (2002–2006)']);
    	Currencies::create(['value' => 'RSD', 'name' => 'Serbiese dinar']);
    	Currencies::create(['value' => 'SCR', 'name' => 'Seychellese rupee']);
    	Currencies::create(['value' => 'SLL', 'name' => 'Sierra Leoniese leone']);
    	Currencies::create(['value' => 'SGD', 'name' => 'Singapoer dollar']);
    	Currencies::create(['value' => 'SHP', 'name' => 'Sint Helena pond']);
    	Currencies::create(['value' => 'SYP', 'name' => 'Siriese pond']);
    	Currencies::create(['value' => 'CNY', 'name' => 'Sjinese joean renminbi']);
    	Currencies::create(['value' => 'SKK', 'name' => 'Slovak Koruna']);
    	Currencies::create(['value' => 'SIT', 'name' => 'Slovenian Tolar']);
    	Currencies::create(['value' => 'SDG', 'name' => 'Soedannese pond']);
    	Currencies::create(['value' => 'SDP', 'name' => 'Soedannese pond (1957–1998)']);
    	Currencies::create(['value' => 'SOS', 'name' => 'Somaliese sjieling']);
    	Currencies::create(['value' => 'ZAL', 'name' => 'South African Rand (financial)']);
    	Currencies::create(['value' => 'KRH', 'name' => 'South Korean Hwan (1953–1962)']);
    	Currencies::create(['value' => 'KRO', 'name' => 'South Korean Won (1945–1953)']);
    	Currencies::create(['value' => 'SUR', 'name' => 'Soviet Rouble']);
    	Currencies::create(['value' => 'ESP', 'name' => 'Spanish Peseta']);
    	Currencies::create(['value' => 'ESA', 'name' => 'Spanish Peseta (A account)']);
    	Currencies::create(['value' => 'ESB', 'name' => 'Spanish Peseta (convertible account)']);
    	Currencies::create(['value' => 'LKR', 'name' => 'Sri Lankaanse roepee']);
    	Currencies::create(['value' => 'SDD', 'name' => 'Sudanese Dinar (1992–2007)']);
    	Currencies::create(['value' => 'ZAR', 'name' => 'Suid-Afrikaanse rand']);
    	Currencies::create(['value' => 'KRW', 'name' => 'Suid-Koreaanse won']);
    	Currencies::create(['value' => 'SSP', 'name' => 'Suid-Soedanese pond']);
    	Currencies::create(['value' => 'SRD', 'name' => 'Surinaamse dollar']);
    	Currencies::create(['value' => 'SRG', 'name' => 'Surinamese Guilder']);
    	Currencies::create(['value' => 'SZL', 'name' => 'Swazilandse lilangeni']);
    	Currencies::create(['value' => 'SEK', 'name' => 'Sweedse kroon']);
    	Currencies::create(['value' => 'CHF', 'name' => 'Switserse frank']);
    	Currencies::create(['value' => 'STD', 'name' => 'São Tomé en Príncipe dobra']);
    	Currencies::create(['value' => 'TJS', 'name' => 'Tadjikse roebel']);
    	Currencies::create(['value' => 'TJR', 'name' => 'Tajikistani Ruble']);
    	Currencies::create(['value' => 'TZS', 'name' => 'Tanzaniese sjieling']);
    	Currencies::create(['value' => 'THB', 'name' => 'Thaise baht']);
    	Currencies::create(['value' => 'TPE', 'name' => 'Timorese Escudo']);
    	Currencies::create(['value' => 'TOP', 'name' => 'Tongaanse pa’anga']);
    	Currencies::create(['value' => 'TTD', 'name' => 'Trinidad en Tobago dollar']);
    	Currencies::create(['value' => 'CZK', 'name' => 'Tsjeggiese kroon']);
    	Currencies::create(['value' => 'TND', 'name' => 'Tunisiese dinar']);
    	Currencies::create(['value' => 'TMT', 'name' => 'Turkmeense manat']);
    	Currencies::create(['value' => 'TMM', 'name' => 'Turkmenistani Manat (1993–2009)']);
    	Currencies::create(['value' => 'TRY', 'name' => 'Turkse lier']);
    	Currencies::create(['value' => 'TRL', 'name' => 'Turkse lier (1922–2005)']);
    	Currencies::create(['value' => 'USN', 'name' => 'US Dollar (Next day)']);
    	Currencies::create(['value' => 'USS', 'name' => 'US Dollar (Same day)']);
    	Currencies::create(['value' => 'UGS', 'name' => 'Ugandan Shilling (1966–1987)']);
    	Currencies::create(['value' => 'UGX', 'name' => 'Ugandese sjieling']);
    	Currencies::create(['value' => 'UAK', 'name' => 'Ukrainian Karbovanets']);
    	Currencies::create(['value' => 'UYU', 'name' => 'Uruguaanse peso']);
    	Currencies::create(['value' => 'UYP', 'name' => 'Uruguayan Peso (1975–1993)']);
    	Currencies::create(['value' => 'UYI', 'name' => 'Uruguayan Peso (Indexed Units)']);
    	Currencies::create(['value' => 'VUV', 'name' => 'Vanuatuse vatu']);
    	Currencies::create(['value' => 'VEF', 'name' => 'Venezolaanse bolivar']);
    	Currencies::create(['value' => 'VEB', 'name' => 'Venezuelan Bolívar (1871–2008)']);
    	Currencies::create(['value' => 'AED', 'name' => 'Verenigde Arabiese Emirate dirham']);
    	Currencies::create(['value' => 'VNN', 'name' => 'Vietnamese Dong (1978–1985)']);
    	Currencies::create(['value' => 'VND', 'name' => 'Viëtnamese dong']);
    	Currencies::create(['value' => 'CHE', 'name' => 'WIR Euro']);
    	Currencies::create(['value' => 'CHW', 'name' => 'WIR Franc']);
    	Currencies::create(['value' => 'YDD', 'name' => 'Yemeni Dinar']);
    	Currencies::create(['value' => 'ISK', 'name' => 'Yslandse kroon']);
    	Currencies::create(['value' => 'YUN', 'name' => 'Yugoslavian Convertible Dinar (1990–1992)']);
    	Currencies::create(['value' => 'YUD', 'name' => 'Yugoslavian Hard Dinar (1966–1990)']);
    	Currencies::create(['value' => 'YUM', 'name' => 'Yugoslavian New Dinar (1994–2002)']);
    	Currencies::create(['value' => 'YUR', 'name' => 'Yugoslavian Reformed Dinar (1992–1993)']);
    	Currencies::create(['value' => 'ZRN', 'name' => 'Zairean New Zaire (1993–1998)']);
    	Currencies::create(['value' => 'ZRZ', 'name' => 'Zairean Zaire (1971–1993)']);
    	Currencies::create(['value' => 'ZMW', 'name' => 'Zambiese kwacha']);
    	Currencies::create(['value' => 'ZMK', 'name' => 'Zambiese kwacha (1968–2012)']);
    	Currencies::create(['value' => 'ZWR', 'name' => 'Zimbabwean Dollar (2008)']);
    	Currencies::create(['value' => 'ZWL', 'name' => 'Zimbabwean Dollar (2009)']);
    	Currencies::create(['value' => 'ZWD', 'name' => 'Zimbabwiese dollar']);
    }
}
